name: Run BERT Sentiment Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'backend/Data/**'

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run BERT sentiment pipeline
      working-directory: backend/preprocessing
      run: |
        python main.py

    - name: Load model
      working-directory: backend/saved_models
      run: |
        python load_model.py

    - name: Upload logs and results (Optional)
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: training-results
        path: |
          backend/Data/results/
          backend/Data/logs/
