name: Run BERT Sentiment Pipeline

on:
  push:
    branches:
      - main  # Trigger action on changes to the main branch
    paths:
      - 'backend/Data/**'  # Trigger only when files in the Data folder are changed

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run BERT sentiment pipeline
      run: |
        python main.py

    - name: Load model and classify comments
      run: |
        python loadmodel.py

    - name: Upload logs and results (Optional)
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: training-results
        path: |
          results/
          logs/
